# bounding box confidence threshold
conf: 0.25
# intersection over union (IoU) threshold for NMS
# (no effect for YOLOv10 models)
iou: 0.7
# NMS IoU threshold for the boxes that have ground truth
# note: it can slow down the post-processing
nms_iou_thresh_with_gt: 0.0
# use half precision (FP16)
half: False
# maximum number of detections per image
max_det: 300
# whether to use class-agnostic NMS or not
agnostic_nms: False
# point confidence threshold (for pose estimation)
point_threshold: 0.1
