# bounding box confidence threshold
conf: 0.25
# intersection over union (IoU) threshold for NMS
# (no effect for YOLOv10 models)
iou: 0.7
# use half precision (FP16)
half: False
# maximum number of detections per image
max_det: 300
# whether to use class-agnostic NMS or not
agnostic_nms: False
# point confidence threshold (for pose estimation)
point_threshold: 0.1
# IoU threshold to filter out predictions that significantly overlap with ground truth objects
# (the greater the value, the fewer predictions will remain)
# If the value is 0.0, no filtering will be done
existing_objects_iou_thresh: 0.0