name: Manual Build App Image From Template
run-name: Manual Build App Image for "${{ github.event.repository.name }}"

on:
  workflow_dispatch:
    inputs:
      tag_version:
        description: "Tag version to build image for"
        required: false
      tag_ref_name:
        description: "Runtime base image tag/ref to use; defaults to tag_version"
        required: false
      enable_cve_checks:
        description: "Enable CVE checks during image build"
        required: false
        type: boolean
        default: true
      skip_tag_check:
        description: "Skip tag existence check before building image"
        required: false
        type: boolean
        default: false
      no_cache_requirements:
        description: "Do not use cache for installing requirements"
        required: false
        type: boolean
        default: false
jobs:
  build-image:
    uses: supervisely-ecosystem/workflows/.github/workflows/build_image_from_template.yml@master
    with:
      tag_version: "${{ inputs.tag_version }}"
      tag_ref_name: "${{ inputs.tag_ref_name }}"
      cve_checks: ${{ inputs.enable_cve_checks }}
      runtime_base_image: "base-py-cuda-hardened"
      extra_builder_libs: "build-essential"
      requirements_file: "train/dev_requirements.txt"
      config_file: "train/config.json"
      skip_tag_check: ${{ inputs.skip_tag_check }}
      no_cache_requirements: ${{ inputs.no_cache_requirements }}
