name: Build App Image From Template (Release)
run-name: Build App Image for "${{ github.event.repository.name }}"

on:
  workflow_dispatch:
    inputs:
      tag_version:
        description: "Tag version to build image for"
        required: false
      cve_checks:
        description: "Run CVE checks on the built image before pushing to registry"
        required: false
        type: boolean
        default: false
jobs:
  build-image:
    uses: supervisely-ecosystem/workflows/.github/workflows/build_image_from_template.yml@per-app-dockerimages
    with:
      image_name: "${{ github.event.repository.name }}"
      tag_version: "${{ github.event.inputs.tag_version }}"
      cve_checks: ${{ inputs.cve_checks }}
      runtime_base_image: "py-cuda-hardened"
      requirements_file: "train/dev_requirements.txt"
