name: Release
run-name: Release version "${{ github.event.release.tag_name }}"
on:
  release:
    types: [published]
    branches:
      - main
      - master
jobs:
  build-image:
    if: "!github.event.release.prerelease"
    uses: supervisely-ecosystem/workflows/.github/workflows/build_image_from_template.yml@master
    with:
      runtime_base_image: "base-py-cuda-hardened"
      image_name: "${{ github.event.repository.name }}"
      requirements_file: "train/dev_requirements.txt"
      config_file: "train/config.json"
      cve_checks: true
  Supervisely-Release:
    if: "!github.event.release.prerelease"
    needs: build-image
    uses: supervisely-ecosystem/workflows/.github/workflows/common.yml@master
    with:
      SUPERVISELY_SERVER_ADDRESS: "${{ vars.SUPERVISELY_DEV_SERVER_ADDRESS }}"
      SUPERVISELY_PROD_SERVER_ADDRESS: "${{ vars.SUPERVISELY_PROD_SERVER_ADDRESS }}"
      SLUG: "${{ github.repository }}"
      RELEASE_VERSION: "${{ github.event.release.tag_name }}"
      RELEASE_DESCRIPTION: "${{ github.event.release.name }}"
      RELEASE_TYPE: "release"
      SUBAPP_PATHS: "__ROOT_APP__"
